pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - author=dependabot[bot]
      - check-success=build=build
      - check-success=build=sonarcloud
    actions:
      merge:
        method: merge
